In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('melb_data.csv')

In [3]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [4]:
df.shape

(13580, 21)

In [5]:
df.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

In [7]:
df.isnull().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

In [8]:
df['Car']=df['Car'].fillna(df['Car'].mode)
df['BuildingArea']=df['BuildingArea'].fillna(df['BuildingArea'].mean)
df['YearBuilt']=df['YearBuilt'].fillna(df['YearBuilt'].mode)
df['CouncilArea']=df['CouncilArea'].fillna(df['CouncilArea'].mode)

In [9]:
df.isnull().sum()

Suburb           0
Address          0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Date             0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
CouncilArea      0
Lattitude        0
Longtitude       0
Regionname       0
Propertycount    0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.dtypes

Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car               object
Landsize         float64
BuildingArea      object
YearBuilt         object
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

In [12]:
df['Address']=df['Address'].astype('string')
df['Suburb']=df['Suburb'].astype('string')

In [13]:
df.dtypes

Suburb           string[python]
Address          string[python]
Rooms                     int64
Type                     object
Price                   float64
Method                   object
SellerG                  object
Date                     object
Distance                float64
Postcode                float64
Bedroom2                float64
Bathroom                float64
Car                      object
Landsize                float64
BuildingArea             object
YearBuilt                object
CouncilArea              object
Lattitude               float64
Longtitude              float64
Regionname               object
Propertycount           float64
dtype: object

In [14]:
df['Date']=pd.to_datetime(df['Date'],errors='coerce')

In [15]:
df.dtypes

Suburb           string[python]
Address          string[python]
Rooms                     int64
Type                     object
Price                   float64
Method                   object
SellerG                  object
Date             datetime64[ns]
Distance                float64
Postcode                float64
Bedroom2                float64
Bathroom                float64
Car                      object
Landsize                float64
BuildingArea             object
YearBuilt                object
CouncilArea              object
Lattitude               float64
Longtitude              float64
Regionname               object
Propertycount           float64
dtype: object

In [16]:
from sklearn.preprocessing import StandardScaler
normalized_price=StandardScaler().fit_transform(df[['Price']])

In [17]:
print(normalized_price)

[[ 0.63244803]
 [-0.06363975]
 [ 0.6089844 ]
 ...
 [ 0.14753294]
 [ 2.22797508]
 [ 0.3274208 ]]

In [18]:
minmax_price=(df['Price']-df['Price'].min())/(df['Price'].max()-df['Price'].min())

In [19]:
print(minmax_price)

0        0.156478
1        0.106562
2        0.154795
3        0.085810
4        0.169938
           ...
13575    0.130118
13576    0.106113
13577    0.121705
13578    0.270892
13579    0.134605
Name: Price, Length: 13580, dtype: float64

In [20]:
df['Type'].value_counts()

Type
h    9449
u    3017
t    1114
Name: count, dtype: int64

In [21]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Type']=le.fit_transform(df['Type'])

In [22]:
print(df['Type'])

0        0
1        0
2        0
3        0
4        0
        ..
13575    0
13576    0
13577    0
13578    0
13579    0
Name: Type, Length: 13580, dtype: int64

In [23]:
df['Type'].value_counts()

Type
0    9449
2    3017
1    1114
Name: count, dtype: int64

In [24]:
one_hot=pd.get_dummies(df['Method'],prefix='Method')

In [25]:
print(one_hot)

       Method_PI  Method_S  Method_SA  Method_SP  Method_VB
0          False      True      False      False      False
1          False      True      False      False      False
2          False     False      False       True      False
3           True     False      False      False      False
4          False     False      False      False       True
...          ...       ...        ...        ...        ...
13575      False      True      False      False      False
13576      False     False      False       True      False
13577      False      True      False      False      False
13578       True     False      False      False      False
13579      False     False      False       True      False

[13580 rows x 5 columns]

In [26]:
dummy_encoding=pd.get_dummies(df['Regionname'],prefix='Region',drop_first=True)

In [27]:
print(dummy_encoding)

       Region_Eastern Victoria  Region_Northern Metropolitan  \
0                        False                          True
1                        False                          True
2                        False                          True
3                        False                          True
4                        False                          True
...                        ...                           ...
13575                    False                         False
13576                    False                         False
13577                    False                         False
13578                    False                         False
13579                    False                         False

       Region_Northern Victoria  Region_South-Eastern Metropolitan  \
0                         False                              False
1                         False                              False
2                         False                              False
3                         False                              False
4                         False                              False
...                         ...                                ...
13575                     False                               True
13576                     False                              False
13577                     False                              False
13578                     False                              False
13579                     False                              False

       Region_Southern Metropolitan  Region_Western Metropolitan  \
0                             False                        False
1                             False                        False
2                             False                        False
3                             False                        False
4                             False                        False
...                             ...                          ...
13575                         False                        False
13576                         False                         True
13577                         False                         True
13578                         False                         True
13579                         False                         True

       Region_Western Victoria
0                        False
1                        False
2                        False
3                        False
4                        False
...                        ...
13575                    False
13576                    False
13577                    False
13578                    False
13579                    False

[13580 rows x 7 columns]

In [28]:
datafinal=pd.concat([df,one_hot,dummy_encoding],axis=1)

In [29]:
datafinal.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Method_SA,Method_SP,Method_VB,Region_Eastern Victoria,Region_Northern Metropolitan,Region_Northern Victoria,Region_South-Eastern Metropolitan,Region_Southern Metropolitan,Region_Western Metropolitan,Region_Western Victoria
0,Abbotsford,85 Turner St,2,0,1480000.0,S,Biggin,2016-03-12,2.5,3067.0,...,False,False,False,False,True,False,False,False,False,False
1,Abbotsford,25 Bloomburg St,2,0,1035000.0,S,Biggin,2016-04-02,2.5,3067.0,...,False,False,False,False,True,False,False,False,False,False
2,Abbotsford,5 Charles St,3,0,1465000.0,SP,Biggin,2017-04-03,2.5,3067.0,...,False,True,False,False,True,False,False,False,False,False
3,Abbotsford,40 Federation La,3,0,850000.0,PI,Biggin,2017-04-03,2.5,3067.0,...,False,False,False,False,True,False,False,False,False,False
4,Abbotsford,55a Park St,4,0,1600000.0,VB,Nelson,2016-04-06,2.5,3067.0,...,False,False,True,False,True,False,False,False,False,False